Branch delete department mergeable
AY2223S2-CS2103T-T17-2/tp pull request #107
Opened 2023-03-17 06:21 UTC by pkwangjoo

- Support DeleteDepartmentCommand
- Cascade deletion of employee to department

2023-03-17 19:04 UTC, kennethk-1201 requested changes

2023-03-18 03:16 UTC, pkwangjoo commented on src/main/java/seedu/sudohr/logic/commands/DeleteCommand.java
> +        departmentList.stream().forEach(d -> d.removeEmployee(employeeToDelete));
done

2023-03-18 04:07 UTC, pkwangjoo commented on src/main/java/seedu/sudohr/logic/parser/DeleteDepartmentCommandParser.java
> +
done

2023-03-18 04:09 UTC, pkwangjoo commented on src/test/java/seedu/sudohr/logic/commands/DeleteCommandTest.java
> +        DeleteCommand deleteCommand = new DeleteCommand(Index.fromZeroBased(indexOfEmployeeToDelete));
noted

2023-03-19 10:48 UTC, kennethk-1201 approved these changes
LGTM

2023-03-20 08:04 UTC, 4ndrelim approved these changes
LGTM. Indexes changes made on my end.

2023-03-20 08:04 UTC, merged