User Guide modifications
AY2223S2-CS2103T-T17-2/tp pull request #291
Opened 2023-04-07 03:46 UTC by jweeyh

2023-04-07 20:36 UTC, kennethk-1201 requested changes
Can you shift the ldhc command from the end of the department section to the end of the leave section, and also in the DG as well. (flows better)

2023-04-07 20:36 UTC, kennethk-1201 commented on docs/UserGuide.md
>  ### 7.1.2. Listing all employees : `list`
Need to update the numbering from 7 to 5

2023-04-09 14:57 UTC, kennethk-1201 approved these changes
LGTM

2023-04-09 15:28 UTC, 4ndrelim approved these changes
LGTM

edit: oops didn't see kiang reviewed agn

2023-04-09 15:28 UTC, merged