Jerren dg update
AY2223S2-CS2103T-T17-2/tp pull request #303
Opened 2023-04-09 13:22 UTC by jerrrren

2023-04-09 14:42 UTC, 4ndrelim requested changes

2023-04-09 14:42 UTC, 4ndrelim commented on docs/DeveloperGuide.md
> +2. The parser will parse the argument and in several fields: Id, name, phone, email, address, and tags, respectively with the prefixes.
"instantiate" is intended here. Parser actually creates these objects

2023-04-09 14:42 UTC, 4ndrelim commented on docs/DeveloperGuide.md
> +2. The parser will instantiates a new `Phone` and `Address` object constructed from the arguments associated with `/p` and `/n`, which represents the new phone number and address fields respectively.
thx for checking grammer but there no 's' for the verb that comes after the word 'will'

2023-04-09 14:42 UTC, 4ndrelim commented on docs/DeveloperGuide.md
> +2. The parser will instantiates the corresponding `Id` object constructed from the argument associated with the prefix `eid/`.
here as well

2023-04-09 14:42 UTC, 4ndrelim commented on docs/DeveloperGuide.md
> +2. The parser would i a new `Id` and `LeaveDate` object constructed from the input of argument `eid/` and `d/` respectively
typo 'i' here?

2023-04-10 08:57 UTC, kennethk-1201 approved these changes
lgtm

2023-04-10 09:00 UTC, merged